apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
    nodePort: 30102
  - name: web
    port: 8025
    targetPort: 8025
    nodePort: 30825